services:
  - type: web
    name: dept-management-server
    env: node
    region: ohio
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
          name: dept-management-server
          key: DATABASE_URL
      - key: DATABASE_HOST
        fromService:
          name: dept-management-server
          key: DATABASE_HOST
      - key: DATABASE_PORT
        fromService:
          name: dept-management-server
          key: DATABASE_PORT
      - key: DATABASE_USER
        fromService:
          name: dept-management-server
          key: DATABASE_USER
      - key: DATABASE_NAME
        fromService:
          name: dept-management-server
          key: DATABASE_NAME
      - key: JWT_SECRET
        fromService:
          name: dept-management-server
          key: JWT_SECRET
      - key: JWT_EXPIRATION
        fromService:
          name: dept-management-server
          key: JWT_EXPIRATION
      - key: PORT
        fromService:
          name: dept-management-server
          key: PORT
      - key: SUPABASE_URL
        fromService:
          name: dept-management-server
          key: SUPABASE_URL
      - key: SUPABASE_KEY
        fromService:
          name: dept-management-server
          key: SUPABASE_KEY
