services:
  - type: web
    name: dept-management-server
    env: node
    region: ohio
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:CtRbY74LRCab26Jp@db.tyrsqsahhyfclmpltnak.supabase.co:5432/postgres
      - key: DB_HOST
        value: db.tyrsqsahhyfclmpltnak.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: postgres
      - key: DB_NAME
        value: postgres
      - key: JWT_SECRET
        value: lkFJ9J8FIOJ9mow987u2f
      - key: JWT_EXPIRATION
        value: 3600
      - key: PORT
        value: 5000
      - key: SUPABASE_URL
        value: https://tyrsqsahhyfclmpltnak.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5cnNxc2FoaHlmY2xtcGx0bmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMDA0OTYsImV4cCI6MjA0OTY3NjQ5Nn0.Fo6K2BN7uvOlUHR0YdlKl4D3j-7Jrn1BWtba0zmlehw